//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.26 at 09:01:52 PM YEKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.flamexander.com/mymarket/ws/products", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.khantemirov.mymarket.soap.products;
